name = "trade-schools"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

# D1 Database binding (commented out until database is created)
# [[d1_databases]]
# binding = "DB"
# database_name = "trade-schools-db"
# database_id = "" # Will be filled after creating database

# Environment variables (set via wrangler secrets)
# RECAPTCHA_SECRET_KEY - Google reCAPTCHA secret key
# RESEND_API_KEY - Resend.com API key for sending emails


