name = "trade-schools"
compatibility_date = "2024-01-01"
pages_build_output_dir = "src"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "trade-schools-db"
database_id = "3c2873d9-f492-4230-aa2d-4a0d95d84a49"

# Environment variables (set via wrangler secrets)
# RECAPTCHA_SECRET_KEY - Google reCAPTCHA secret key
# RESEND_API_KEY - Resend.com API key for sending emails


